# Generated by Django 5.1.3 on 2024-11-29 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_licitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_tecnico', models.PositiveIntegerField()),
                ('puntaje_economico', models.PositiveIntegerField()),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('fecha_presentacion', models.DateTimeField(auto_now_add=True)),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='gestion_licitaciones.licitacion')),
            ],
        ),
    ]
