# Generated by Django 5.1.3 on 2024-11-29 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propuestas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='proveedor',
            field=models.ForeignKey(limit_choices_to={'rol': 'proveedor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='propuesta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propuestas.propuesta'),
        ),
    ]
