# Generated by Django 5.1.3 on 2024-12-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='ganadora',
            field=models.BooleanField(default=False),
        ),
    ]
